### ISSUE TITLE
Preparation for new PICO project

### ISSUE THREAD

**Issue by danielwolff1** [imcs-compsim/pinns_for_comp_mech#33]
In preparation of the new PICO project with external collaboration partners, we have to make some minor modifications to the current repository. After making up my mind for a long time, I came up with the following roadmap that should interfere with the current developments and ongoing research as little as possible.

# A) Create empty `collab-release` branch

We identify the first commit in the repository and roll back to this state. Once we have done this, for future reference, we create a tag pointing to the root state of the repository. 
```shell
$ git checkout -b collab-release
$ git rev-list --max-parents=0 --abbrev-commit HEAD
07b8758
$ git reset --hard 07b8758
$ git push -f --set-upstream origin collab-release
$ git tag -a -m '' ROOT
$ git push origin ROOT
```

# B) Create release repository 
This (initially empty) release repository is the one which will be shared with our collaborators. We will probably create it in the same organization but make it private so that only selected people can access it.

 # C) Automize release of changes
We will setup a GitHub Actions workflow to automatically synchronise the `collab-release` branch of this repository and the `main` branch of the collab repository created in step B). 
A corresponding yaml configuration file for the GitHub Actions Workflow could look like this

<details>
<summary> .github/workflows/push-to-collab.yaml </summary>

```yaml
name: Push Selected Files to Collaboration Repo

on:
  push:
    branches:
      - collab-release

jobs:
  sync-to-collab-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo (this one)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: collab-release

      - name: Clone the collaboration repository
        run: |
          git clone https://x-access-token:${{ secrets.COLLAB_PUSH_TOKEN }}@github.com/danielwolff1/test-release.git ../collab-repo

      - name: Rsync selected folders into collaboration repo
        run: |
          rsync -av --delete src/ ../collab-repo/src/
          rsync -av --delete examples/ ../collab-repo/examples/
          rsync -av --delete tests/ ../collab-repo/tests/
        # `--delete` ensures removed files are also deleted in the target

      - name: Commit and push changes to collab repo
        working-directory: ../collab-repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          
          git add src/ examples/ tests/
          if ! git diff --cached --quiet; then
            git commit -m "Sync from collab-release branch"
            git push origin main
          else
            echo "No changes to commit"
          fi
```

</details>

This file will be created in the `main` branch of this repository and then the respective commit will be cherry-picked on the `collab-release` branch.

# D) Development of new features with the new structure
Development of new features for individual PhD projects can and should be continued just like before: You create feature branches, develop your features and bring them back to main via a pull-requests.

As for the development of features / documentation for the collaboration: We will create special feature branches for the milestones of the collaboration, e.g., 
```
git checkout -b ft-4-collab-release-milestone-25q1
```
On these branches we can checkout special features from `main`, e.g., 
```
git checkout main -- utils/elasticity/elasticity_utils.py
``` 
and commit them first to the feature branch before this feature branch will finally be merged into `collab-release`: 
```
git checkout collab-release
git merge ft-4-collab-release-milestone-25q1 --no-ff
git push
```
This last step will then trigger the previously defined action and create a commit to the collaboration repository so that the collaborators get a new version to work with.
